export interface SimulatedActionEffects {
  actionName: string;
  fuelDelta: number;
  powerDelta: number;
  oxygenDelta: number;
  healthDelta: number;
  progressDelta: number;
  crewHealthDelta: number;
  crewMoraleDelta: number;
  successImpact: number;
  benefits: string;
  risks: string;
  communicationRestore?: boolean;
  velocityRestore?: boolean;
  velocityDelta?: number;
}

export type EventSimulationModel = Record<string, SimulatedActionEffects>;

export const SIMULATION_MODELS: Record<string, EventSimulationModel> = {
  "Fuel Leak": {
    "Ignore": {
      actionName: "Ignore",
      fuelDelta: -15,
      powerDelta: 0,
      oxygenDelta: 0,
      healthDelta: -5,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: -10,
      successImpact: -15,
      benefits: "No immediate power or oxygen draw.",
      risks: "Rapid fuel loss leading to thruster failure, crew panic.",
    },
    "Reduce Speed": {
      actionName: "Reduce Speed",
      fuelDelta: -5,
      powerDelta: -2,
      oxygenDelta: 0,
      healthDelta: 0,
      progressDelta: -2,
      crewHealthDelta: 0,
      crewMoraleDelta: -3,
      successImpact: -2,
      benefits: "Reduces fuel pressure, slowing down leak rate.",
      risks: "Slight delay in timeline progression.",
      velocityDelta: -20,
    },
    "Activate Backup Tank": {
      actionName: "Activate Backup Tank",
      fuelDelta: 10,
      powerDelta: -4,
      oxygenDelta: 0,
      healthDelta: 2,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: 5,
      successImpact: 10,
      benefits: "Engages backup reserves, fully stabilizing fuel lines.",
      risks: "Draws power to operate transfer pumps.",
    },
  },
  "Solar Storm": {
    "Continue Mission": {
      actionName: "Continue Mission",
      fuelDelta: 0,
      powerDelta: -12,
      oxygenDelta: 0,
      healthDelta: -8,
      progressDelta: 1,
      crewHealthDelta: -20,
      crewMoraleDelta: -15,
      successImpact: -15,
      benefits: "Maintains flight plan velocity and progress.",
      risks: "Severe radiation sickness in crew, solar panel damage.",
    },
    "Change Route": {
      actionName: "Change Route",
      fuelDelta: -10,
      powerDelta: -3,
      oxygenDelta: 0,
      healthDelta: -1,
      progressDelta: 0,
      crewHealthDelta: -2,
      crewMoraleDelta: -5,
      successImpact: 4,
      benefits: "Steers around core storm radiation corridor.",
      risks: "High fuel consumption during trajectory burn.",
    },
    "Enter Safe Mode": {
      actionName: "Enter Safe Mode",
      fuelDelta: 0,
      powerDelta: 6,
      oxygenDelta: -1,
      healthDelta: 0,
      progressDelta: -3,
      crewHealthDelta: 0,
      crewMoraleDelta: -2,
      successImpact: 12,
      benefits: "Protects avionics and cabin shields, reboots battery.",
      risks: "Pauses progression, minor oxygen load.",
      communicationRestore: true,
    },
  },
  "Engine Failure": {
    "Ignore": {
      actionName: "Ignore",
      fuelDelta: -4,
      powerDelta: -5,
      oxygenDelta: 0,
      healthDelta: -12,
      progressDelta: -5,
      crewHealthDelta: -5,
      crewMoraleDelta: -12,
      successImpact: -20,
      benefits: "Saves backup equipment wear.",
      risks: "Unstable exhaust triggers structural damage, catastrophic speed drop.",
    },
    "Reduce Speed": {
      actionName: "Reduce Speed",
      fuelDelta: -1,
      powerDelta: -2,
      oxygenDelta: 0,
      healthDelta: -2,
      progressDelta: -2,
      crewHealthDelta: 0,
      crewMoraleDelta: -4,
      successImpact: -5,
      benefits: "Prevents thermal engine block runaway.",
      risks: "Reduces thrust and delays travel velocity.",
    },
    "Activate Backup Engine": {
      actionName: "Activate Backup Engine",
      fuelDelta: -3,
      powerDelta: -5,
      oxygenDelta: 0,
      healthDelta: 5,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: 8,
      successImpact: 15,
      benefits: "Restores normal nominal cruise thrust vectors.",
      risks: "Requires high power sequence load during start.",
      velocityRestore: true,
    },
  },
  "Oxygen Leak": {
    "Ignore": {
      actionName: "Ignore",
      fuelDelta: 0,
      powerDelta: 0,
      oxygenDelta: -20,
      healthDelta: -15,
      progressDelta: 0,
      crewHealthDelta: -25,
      crewMoraleDelta: -20,
      successImpact: -25,
      benefits: "Conserves robot battery packs.",
      risks: "Rapid hull venting leading to crew hypoxia and cabin failure.",
    },
    "Seal Leak": {
      actionName: "Seal Leak",
      fuelDelta: 0,
      powerDelta: -3,
      oxygenDelta: -4,
      healthDelta: 5,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: 5,
      successImpact: 10,
      benefits: "Directly patches the breach in the module wall.",
      risks: "Drains battery to run maintenance nanites.",
    },
    "Switch Life Support Backup": {
      actionName: "Switch Life Support Backup",
      fuelDelta: 0,
      powerDelta: -6,
      oxygenDelta: 15,
      healthDelta: 8,
      progressDelta: 0,
      crewHealthDelta: 10,
      crewMoraleDelta: 12,
      successImpact: 18,
      benefits: "Isolates the leaking chamber and pressurizes reserves.",
      risks: "Draws sustained higher load on reactor batteries.",
    },
  },
  "Battery Failure": {
    "Continue Operations": {
      actionName: "Continue Operations",
      fuelDelta: 0,
      powerDelta: -15,
      oxygenDelta: -5,
      healthDelta: -5,
      progressDelta: 0,
      crewHealthDelta: -5,
      crewMoraleDelta: -10,
      successImpact: -18,
      benefits: "Avoids systems power re-routing delay.",
      risks: "Risk of complete grid blackout, cold temperatures.",
    },
    "Divert Nonessential Power": {
      actionName: "Divert Nonessential Power",
      fuelDelta: 0,
      powerDelta: 5,
      oxygenDelta: 0,
      healthDelta: 0,
      progressDelta: -1,
      crewHealthDelta: 0,
      crewMoraleDelta: -3,
      successImpact: 4,
      benefits: "Preserves lifelines by switching off secondary grids.",
      risks: "Shuts down high-gain sensors and external mapping.",
    },
    "Switch Backup Battery": {
      actionName: "Switch Backup Battery",
      fuelDelta: -2,
      powerDelta: 18,
      oxygenDelta: 0,
      healthDelta: 5,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: 8,
      successImpact: 15,
      benefits: "Engages emergency backup cells, restoring normal voltage.",
      risks: "Attitude thruster jet burn needed for re-alignment.",
    },
  },
  "Navigation Error": {
    "Ignore": {
      actionName: "Ignore",
      fuelDelta: 0,
      powerDelta: 0,
      oxygenDelta: 0,
      healthDelta: 0,
      progressDelta: -10,
      crewHealthDelta: 0,
      crewMoraleDelta: -8,
      successImpact: -12,
      benefits: "Saves thruster fuel.",
      risks: "Continuous drift from trajectory corridor.",
    },
    "Recalculate Route": {
      actionName: "Recalculate Route",
      fuelDelta: -6,
      powerDelta: -2,
      oxygenDelta: 0,
      healthDelta: 0,
      progressDelta: 6,
      crewHealthDelta: 0,
      crewMoraleDelta: 5,
      successImpact: 10,
      benefits: "Re-aligns velocity vectors with Adriatic targets.",
      risks: "Requires minor engine correction burns.",
    },
    "Maintain Current Path": {
      actionName: "Maintain Current Path",
      fuelDelta: -2,
      powerDelta: -1,
      oxygenDelta: 0,
      healthDelta: 0,
      progressDelta: -3,
      crewHealthDelta: 0,
      crewMoraleDelta: -2,
      successImpact: -2,
      benefits: "Lower fuel expenditure than full course corrections.",
      risks: "Increases travel flight time and delays entry.",
    },
  },
  "Radiation Spike": {
    "Ignore": {
      actionName: "Ignore",
      fuelDelta: 0,
      powerDelta: 0,
      oxygenDelta: 0,
      healthDelta: -5,
      progressDelta: 0,
      crewHealthDelta: -18,
      crewMoraleDelta: -12,
      successImpact: -15,
      benefits: "Maintains shield sensor profiles.",
      risks: "Severe radiation sickness and mutation cell risks for crew.",
    },
    "Shield Crew": {
      actionName: "Shield Crew",
      fuelDelta: 0,
      powerDelta: -8,
      oxygenDelta: 0,
      healthDelta: 2,
      progressDelta: 0,
      crewHealthDelta: 8,
      crewMoraleDelta: 5,
      successImpact: 10,
      benefits: "Runs active magnetic shielding overlay cells.",
      risks: "High sustained draw on core generator power.",
    },
    "Enter Safe Mode": {
      actionName: "Enter Safe Mode",
      fuelDelta: -2,
      powerDelta: -3,
      oxygenDelta: -2,
      healthDelta: 5,
      progressDelta: -3,
      crewHealthDelta: 10,
      crewMoraleDelta: 4,
      successImpact: 12,
      benefits: "Aligns structural shields with radiation vector source.",
      risks: "Pauses flight plan velocity and limits oxygen.",
    },
  },
  "Communication Loss": {
    "Ignore": {
      actionName: "Ignore",
      fuelDelta: 0,
      powerDelta: 0,
      oxygenDelta: 0,
      healthDelta: 0,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: -10,
      successImpact: -10,
      benefits: "No immediate equipment power load.",
      risks: "Complete isolation from Earth command and objective logs.",
    },
    "Restart Systems": {
      actionName: "Restart Systems",
      fuelDelta: 0,
      powerDelta: -5,
      oxygenDelta: -2,
      healthDelta: 0,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: 2,
      successImpact: 5,
      benefits: "Forces cold reboot, clearing corrupted cache blocks.",
      risks: "Brief life support circulation cutout.",
    },
    "Use Backup Antenna": {
      actionName: "Use Backup Antenna",
      fuelDelta: -1,
      powerDelta: -3,
      oxygenDelta: 0,
      healthDelta: 2,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: 6,
      successImpact: 10,
      benefits: "Deploys secondary high-gain antenna arrays.",
      risks: "Mechanical deployment burns minor fuel.",
      communicationRestore: true,
    },
  },
  "Asteroid Field": {
    "Maintain Speed": {
      actionName: "Maintain Speed",
      fuelDelta: 0,
      powerDelta: 0,
      oxygenDelta: 0,
      healthDelta: -15,
      progressDelta: 0,
      crewHealthDelta: -10,
      crewMoraleDelta: -15,
      successImpact: -18,
      benefits: "Maintains current cruise progress speed.",
      risks: "High collision hazards, catastrophic hull failure risks.",
    },
    "Slow Down": {
      actionName: "Slow Down",
      fuelDelta: -4,
      powerDelta: -2,
      oxygenDelta: 0,
      healthDelta: -2,
      progressDelta: -2,
      crewHealthDelta: 0,
      crewMoraleDelta: -2,
      successImpact: 6,
      benefits: "Reduces impact momentum, minimizing collision forces.",
      risks: "Slows velocity, burning braking fuel.",
    },
    "Change Course": {
      actionName: "Change Course",
      fuelDelta: -8,
      powerDelta: -3,
      oxygenDelta: 0,
      healthDelta: 8,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: 8,
      successImpact: 12,
      benefits: "Navigates clean bypass corridor, restoring shield vectors.",
      risks: "High thruster fuel burn for trajectory diversion.",
      velocityRestore: true,
    },
  },
  "Unknown Object Detected": {
    "Ignore": {
      actionName: "Ignore",
      fuelDelta: 0,
      powerDelta: 0,
      oxygenDelta: 0,
      healthDelta: 0,
      progressDelta: 0,
      crewHealthDelta: 0,
      crewMoraleDelta: -3,
      successImpact: 0,
      benefits: "Maintains absolute course vectors.",
      risks: "Zero scientific data gathered.",
    },
    "Scan Object": {
      actionName: "Scan Object",
      fuelDelta: 0,
      powerDelta: -4,
      oxygenDelta: 0,
      healthDelta: 0,
      progressDelta: 2,
      crewHealthDelta: 0,
      crewMoraleDelta: 3,
      successImpact: 5,
      benefits: "Gathers spectroscopy data safely at distance.",
      risks: "Slight reactor power drain to run scanners.",
    },
    "Investigate": {
      actionName: "Investigate",
      fuelDelta: -5,
      powerDelta: -6,
      oxygenDelta: 0,
      healthDelta: -4,
      progressDelta: 4,
      crewHealthDelta: 0,
      crewMoraleDelta: 8,
      successImpact: 10,
      benefits: "Maximizes Adriatic scientific data and records.",
      risks: "Unforeseen field effects strain structural plating.",
    },
  },
};
